<?php
/**
 * Created by PhpStorm.
 * User: Sclif
 * Date: 05.02.2018
 * Time: 15:33
 */

namespace MyNewProject\MySiteOnClasses\Controllers;

use MyNewProject\MySiteOnClasses\ModelAuth as Model;

use MyNewProject\MySiteOnClasses\Session as Session;

class AuthController extends Controller
{
    public $page_description = 'Страница Авторизации';
    public $page_title = 'Авторизация';
    public $page_view = '../private/View/auth_view.php';

    private $users_file = '../data/users_list.txt';

    function __construct()
    {
        $page_title = $this->page_title;
        $page_description = $this->page_description;
        $page_view = $this->page_view;
        parent::__construct($page_title, $page_description, $page_view);
    }
    function index()
    {
        parent::index(); // TODO: Change the autogenerated stub
    }
    function authUser(){
           var_dump($_POST);
//        $post = $_POST['reg_users_data'];
//        $user_data = json_decode($post,true);
//        $new_user = new Model($this->users_file,$user_data);
//        $new_user->filterInputData();
//        $new_user->authUsers();
    }
    function regUser(){
            var_dump($_POST);
    }
}